#!/bin/bash
#
#

set -xe

# generate boot.img
dd if=/dev/zero of=boot.img bs=1M count=512
mkfs.ext2 -U 7A3F0000-0000-446A-8000-702F00006273 -L kdevboot boot.img
mount boot.img /mnt

mkdir -p /mnt/dtb
cp -a d3588.dtb /mnt/dtb/
cp -f ./arch/arm64/boot/Image /mnt/vmlinuz-5.10.198-kdev
cp -f .config /mnt/config-5.10.198-kdev
cp -f System.map /mnt/System.map-5.10.198-kdev
touch /mnt/initrd.img-5.10.198-kdev

cp ../official-firmware/rk3588dt-l14-oem-debian11-250214/Image /mnt/
cp ../official-firmware/rk3588dt-l14-oem-debian11-250214/d3588.dtb /mnt/


cat >/mnt/extlinux.conf <<EOF
## /extlinux/extlinux.conf
##
## IMPORTANT WARNING
##
## The configuration of this file is generated automatically.
## Do not edit this file manually, use: u-boot-update

default l0
menu title Kdev U-Boot menu
prompt 1
timeout 90


label l0
	menu label Linux kernel 5.10.198-kdev
	linux vmlinuz-5.10.198-kdev
	initrd initrd.img-5.10.198-kdev
	fdt /dtb/d3588.dtb
	append root=PARTUUID=614e0000-0000-4b53-8000-1d28000054a9 rootwait rw console=ttyS2,1500000 console=tty1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory net.ifnames=0 biosdevname=0 level=10 loglevel=10 selinux=0 crashkernel=384M-:128M systemd.mask=systemd-growfs@-.service rockchip.dmc_freq=528000 video=HDMI-A-1:1920x1080@60

label l0r
	menu label Linux kernel 5.10.198-kdev (rescue target)
	linux vmlinuz-5.10.198-kdev
	initrd initrd.img-5.10.198-kdev
	fdt /dtb/d3588.dtb
	append root=PARTUUID=614e0000-0000-4b53-8000-1d28000054a9 rootwait rw console=ttyS2,1500000 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory net.ifnames=0 biosdevname=0 level=10 loglevel=10 selinux=0 crashkernel=384M-:128M single


label l0r
	menu label Linux kernel 5.10.198 (official)
	linux Image
	initrd initrd.img-5.10.198-kdev
	fdt /d3588.dtb
	append root=PARTUUID=614e0000-0000-4b53-8000-1d28000054a9 rootwait rw console=ttyS2,1500000 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory net.ifnames=0 biosdevname=0 level=10 loglevel=10 selinux=0 crashkernel=384M-:128M


EOF

cat >/mnt/armbian_first_run.txt <<EOF
root_password=admin
username=admin
user_password=admin
shell=bash

EOF

find /mnt
sync
umount /mnt
sync

ls -alh boot.img
md5sum boot.img

tar -zcvf boot.img.tar.gz boot.img
ls -alh boot.img.tar.gz

echo "All done!"

